### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.mob.socketservice.ServiceMessageData" 

### ISSUE THREAD

**Issue by ykrank** [MobClub/MobPush-For-Flutter#19]
从1.1.4升级到1.1.5后，Android就会有这个崩溃。是不是proguard的问题？

**Comment by yuwenjian** [comment]
可以清楚下缓存，或者更新下版本

**Comment by ykrank** [comment]
已经解决了，是mob sdk版本的问题。之前写死了使用2020.0703.1640。这次更新后需要使用'com.mob.sdk:MobSDK-Impl:2020.0720.2015'
