### ISSUE TITLE
使用使用flutter build apk --target-platform android-arm --split-per-abi打包命令生成的release包，获取不到registrationId

### ISSUE THREAD

**Issue by qinkaiabc** [MobClub/MobPush-For-Flutter#20]
使用新Flutter新插件mobpush_plugin 1.1.5。
使用flutter build apk --target-platform android-arm --split-per-abi打包命令生成的release包，
调用MobpushPlugin.getRegistrationId()获取不到registrationId，返回为null.

**Comment by qinkaiabc** [comment]
问题解决。
原因是：flutter build apk --target-platform android-arm --split-per-abi打包命令不会读取
build.gradle中的MobSDK {
    appKey "xxx"
    appSecret "xxx"}
中的配置，换成MobSDK.init(this,"appkey","appsecrt")初始化信息就可以了

**Comment by saviourdog** [comment]
> 问题解决。
> 原因是：flutter build apk --target-platform android-arm --split-per-abi打包命令不会读取
> build.gradle中的MobSDK {
> appKey "xxx"
> appSecret "xxx"}
> 中的配置，换成MobSDK.init(this,"appkey","appsecrt")初始化信息就可以了

kotlin的项目在哪改呢
