### ISSUE TITLE
打包时开启混淆厂商推送不可用

### ISSUE THREAD

**Issue by sweatfryash** [MobClub/MobPush-For-Flutter#24]
关闭混淆就可以正常了 #8 有issue提到了按照文档wiki的配置解决，但是那个链接点进去已经没有关于配置混淆的内容了。

**Comment by saviourdog** [comment]
大兄弟解决了吗

**Comment by sweatfryash** [comment]
自己配置混淆文件，在混淆文件中加入下面这些代码，应该就是说不混淆这些包的代码就好了。


-dontwarn com.meizu.**

#xiaomi
-keep class com.xiaomi.**{*;}
-dontwarn com.xiaomi.**
-keep class org.apache.thrift.**{*;}
-keep class android.os.SystemProperties
-dontwarn android.os.SystemProperties

#FCM
-keep class com.google.**{*;}
-dontwarn com.google.**

#VIVO
-keep class com.vivo.push.**{*; }
-keep class com.vivo.vms.**{*; }
-dontwarn com.vivo.push.**

#OPPO
-keep class com.coloros.** {*;}
-dontwarn com.coloros.**

**Comment by saviourdog** [comment]
[这个问题](https://github.com/MobClub/MobPush-For-Flutter/issues/16)配置混淆能解决吗

**Comment by saviourdog** [comment]
> 自己配置混淆文件，在混淆文件中加入下面这些代码，应该就是说不混淆这些包的代码就好了。
> 
> -dontwarn com.meizu.**
> 
> #xiaomi
> -keep class com.xiaomi.**{*;} -dontwarn com.xiaomi.**
> -keep class org.apache.thrift.**{*;}
> -keep class android.os.SystemProperties
> -dontwarn android.os.SystemProperties
> 
> #FCM
> -keep class com.google.**{*;} -dontwarn com.google.**
> 
> #VIVO
> -keep class com.vivo.push.**{*; } -keep class com.vivo.vms.**{*; }
> -dontwarn com.vivo.push.**
> 
> #OPPO
> -keep class com.coloros.** {*;}
> -dontwarn com.coloros.**

[这个问题](https://github.com/MobClub/MobPush-For-Flutter/issues/16)配置混淆能解决吗

**Comment by sweatfryash** [comment]
我不太方便测试，方便的兄弟们进行下测试吧
