### ISSUE TITLE
啊?plugin 代码是在 example写的????

### ISSUE THREAD

**Issue by sm9i** [MobClub/MobPush-For-Flutter#4]
测试了半天 接收不到消息........

**Comment by sm9i** [comment]
大哥们..该发包了....pub和 git 不是一个版本了...

**Comment by lishuzhi1121** [comment]
> 大哥们..该发包了....pub和 git 不是一个版本了...

大佬别喷，已经全力在做了，之前的版本在iOS Swift 的Flutter项目中使用是有问题的，所以才更新了一把。

**Comment by lishuzhi1121** [comment]
> 测试了半天 接收不到消息........

plugin 的代码在mobpush_plugin.dart 里的啊，example里是我们的demo

**Comment by sm9i** [comment]
我不是在喷.....只是 如果吧 init 写在app目录的话  app和插件都会依赖Mob 我觉得 你应该吧  init  抽出来 写在插件里  然后不同厂商 建议在 插件里配,  在 gradle 配置的话 有问题...

**Comment by sm9i** [comment]
> > 测试了半天接收不到消息........
> 
> plugin的代码在mobpush_plugin.dart里的啊，示例里是我们的demo

我知道..但你android 没有具体实现啊...

**Comment by lishuzhi1121** [comment]
> 测试了半天 接收不到消息.......

> 我不是在喷.....只是 如果吧 init 写在app目录的话 app和插件都会依赖Mob 我觉得 你应该吧 init 抽出来 写在插件里 然后不同厂商 建议在 插件里配, 在 gradle 配置的话 有问题...

呃，你好像是在说安卓的问题，安卓这边我不是很熟悉，但是iOS这边我是调试过，没有问题的，安卓这边你可以联系Mob官方技术支持咨询一下呢。

**Comment by sm9i** [comment]
> > 测试了半天接收不到消息.......
> 
> > 我不是在喷.....只是如果吧init写在app目录的话app和插件都会依赖Mob我觉得你应该吧init抽出来写在插件里然后不同厂商建议在插件里配，在gradle配置的话有问题...
> 
> 呃，你好像是在说安卓的问题，安卓这边我不是很熟悉，但是iOS的这边我是调试过，没有问题的，安卓这边你可以联系暴民官方技术支持咨询一下呢。

哦 .看到了..ios有实现..android 没有实现.

**Comment by lishuzhi1121** [comment]
> > > 测试了半天接收不到消息........
> > 
> > 
> > plugin的代码在mobpush_plugin.dart里的啊，示例里是我们的demo
> 
> 我知道..但你android 没有具体实现啊...

哦，Sorry，这个plugin还在完善，安卓那边还在同步，请稍等，稍后我们会把安卓同步更新上去的。感谢你的支持。
