### ISSUE TITLE
No implementation found for method listen on channel mobpush_receiver

### ISSUE THREAD

**Issue by 2000calories** [MobClub/MobPush-For-Flutter#6]
https://pub.dev/packages/mobpush 跟着文档配置，打包成功，但是调用Mobpush就会出现error。**MissingPluginException(No implementation found for method getRegistrationId on channel mob.com/mobpush)**。

以下是console log：
Launching lib\main.dart on Android SDK built for x86 in debug mode...
=============================
=== MobSDK 2019.0909.1445 ===
=============================
Built build\app\outputs\apk\debug\app-debug.apk.
E/flutter (31995): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method getRegistrationId on channel mob.com/mobpush)
[38;5;244mE/flutter (31995): #0      MethodChannel.invokeMethod[39;49m
E/flutter (31995): <asynchronous suspension>
[38;5;248mE/flutter (31995): #1      Mobpush.getRegistrationId[39;49m
E/flutter (31995): <asynchronous suspension>
[38;5;248mE/flutter (31995): #2      _MyAppState.initState[39;49m
[38;5;244mE/flutter (31995): #3      StatefulElement._firstBuild[39;49m
[38;5;244mE/flutter (31995): #4      ComponentElement.mount[39;49m
[38;5;244mE/flutter (31995): #5      Element.inflateWidget[39;49m
[38;5;244mE/flutter (31995): #6      Element.updateChild[39;49m
[38;5;244mE/flutter (31995): #7      ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (31995): #8      Element.rebuild[39;49m
[38;5;244mE/flutter (31995): #9      ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter (31995): #10     ComponentElement.mount[39;49m
[38;5;244mE/flutter (31995): #11     Element.inflateWidget[39;49m
[38;5;244mE/flutter (31995): #12     Element.updateChild[39;49m
[38;5;244mE/flutter (31995): #13     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (31995): #14     Element.rebuild[39;49m
[38;5;244mE/flutter (31995): #15     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter (31995): #16     StatefulElement._firstBuild[39;49m
[38;5;244mE/flutter (31995): #17     ComponentElement.mount[39;49m
[38;5;244mE/flutter (31995): #18     Element.inflateWidget[39;49m
[38;5;244mE/flutter (31995): #19     Element.updateChild[39;49m
[38;5;244mE/flutter (31995): #20     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (31995): #21     Element.rebuild[39;49m
[38;5;244mE/flutter (31995): #22     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter (31995): #23     ComponentElement.mount[39;49m
[38;5;244mE/flutter (31995): #24     Element.inflateWidget[39;49m
[38;5;244mE/flutter (31995): #25     Element.updateChild[39;49m
[38;5;244mE/flutter (31995): #26     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (31995): #27     Element.rebuild[39;49m
[38;5;244mE/flutter (31995): #28     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter (31995): #29     StatefulElement._firstBuild[39;49m
[38;5;244mE/flutter (31995): #30     ComponentElement.mount[39;49m
[38;5;244mE/flutter (31995): #31     Element.inflateWidget[39;49m
[38;5;244mE/flutter (31995): #32     Element.updateChild[39;49m
[38;5;244mE/flutter (31995): #33     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (31995): #34     Element.rebuild[39;49m
[38;5;244mE/flutter (31995): #35     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter (31995): #36     ComponentElement.mount[39;49m
[38;5;244mE/flutter (31995): #37     Element.inflateWidget[39;49m
[38;5;244mE/flutter (31995): #38     Element.updateChild[39;49m
[38;5;244mE/flutter (31995): #39     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (31995): #40     Element.rebuild[39;49m
[38;5;244mE/flutter (31995): #41     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter (31995): #42     StatefulElement._firstBuild[39;49m
[38;5;244mE/flutter (31995): #43     ComponentElement.mount[39;49m
[38;5;244mE/flutter (31995): #44     Element.inflateWidget[39;49m
E/flutter (31995): #45     Element.updateChild (package:flutter/src/widge

[38;5;248m════════ Exception Caught By services library ══════════════════════════════════[39;49m
[38;5;244mThe following MissingPluginException was thrown while activating platform stream on channel mobpush_receiver:[39;49m
[38;5;244mMissingPluginException(No implementation found for method listen on channel mobpush_receiver)[39;49m
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      MethodChannel.invokeMethod[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;244m#1      EventChannel.receiveBroadcastStream.<anonymous closure>[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#6      Mobpush.addPushReceiver[39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

**Comment by lijianqiang12** [comment]
> https://pub.dev/packages/mobpush 跟着文档配置，打包成功，但是调用Mobpush就会出现error。**MissingPluginException(No implementation found for method getRegistrationId on channel mob.com/mobpush)**。
> 
> # 以下是console log：
> Launching lib\main.dart on Android SDK built for x86 in debug mode...
> # === MobSDK 2019.0909.1445 ===
> Built build\app\outputs\apk\debug\app-debug.apk.
> E/flutter (31995): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method getRegistrationId on channel mob.com/mobpush)
> �[38;5;244mE/flutter (31995): #0 MethodChannel.invokeMethod�[39;49m
> E/flutter (31995):
> �[38;5;248mE/flutter (31995): #1 Mobpush.getRegistrationId�[39;49m
> E/flutter (31995):
> �[38;5;248mE/flutter (31995): #2 _MyAppState.initState�[39;49m
> �[38;5;244mE/flutter (31995): #3 StatefulElement._firstBuild�[39;49m
> �[38;5;244mE/flutter (31995): #4 ComponentElement.mount�[39;49m
> �[38;5;244mE/flutter (31995): #5 Element.inflateWidget�[39;49m
> �[38;5;244mE/flutter (31995): #6 Element.updateChild�[39;49m
> �[38;5;244mE/flutter (31995): #7 ComponentElement.performRebuild�[39;49m
> �[38;5;244mE/flutter (31995): #8 Element.rebuild�[39;49m
> �[38;5;244mE/flutter (31995): #9 ComponentElement._firstBuild�[39;49m
> �[38;5;244mE/flutter (31995): #10 ComponentElement.mount�[39;49m
> �[38;5;244mE/flutter (31995): #11 Element.inflateWidget�[39;49m
> �[38;5;244mE/flutter (31995): #12 Element.updateChild�[39;49m
> �[38;5;244mE/flutter (31995): #13 ComponentElement.performRebuild�[39;49m
> �[38;5;244mE/flutter (31995): #14 Element.rebuild�[39;49m
> �[38;5;244mE/flutter (31995): #15 ComponentElement._firstBuild�[39;49m
> �[38;5;244mE/flutter (31995): #16 StatefulElement._firstBuild�[39;49m
> �[38;5;244mE/flutter (31995): #17 ComponentElement.mount�[39;49m
> �[38;5;244mE/flutter (31995): #18 Element.inflateWidget�[39;49m
> �[38;5;244mE/flutter (31995): #19 Element.updateChild�[39;49m
> �[38;5;244mE/flutter (31995): #20 ComponentElement.performRebuild�[39;49m
> �[38;5;244mE/flutter (31995): #21 Element.rebuild�[39;49m
> �[38;5;244mE/flutter (31995): #22 ComponentElement._firstBuild�[39;49m
> �[38;5;244mE/flutter (31995): #23 ComponentElement.mount�[39;49m
> �[38;5;244mE/flutter (31995): #24 Element.inflateWidget�[39;49m
> �[38;5;244mE/flutter (31995): #25 Element.updateChild�[39;49m
> �[38;5;244mE/flutter (31995): #26 ComponentElement.performRebuild�[39;49m
> �[38;5;244mE/flutter (31995): #27 Element.rebuild�[39;49m
> �[38;5;244mE/flutter (31995): #28 ComponentElement._firstBuild�[39;49m
> �[38;5;244mE/flutter (31995): #29 StatefulElement._firstBuild�[39;49m
> �[38;5;244mE/flutter (31995): #30 ComponentElement.mount�[39;49m
> �[38;5;244mE/flutter (31995): #31 Element.inflateWidget�[39;49m
> �[38;5;244mE/flutter (31995): #32 Element.updateChild�[39;49m
> �[38;5;244mE/flutter (31995): #33 ComponentElement.performRebuild�[39;49m
> �[38;5;244mE/flutter (31995): #34 Element.rebuild�[39;49m
> �[38;5;244mE/flutter (31995): #35 ComponentElement._firstBuild�[39;49m
> �[38;5;244mE/flutter (31995): #36 ComponentElement.mount�[39;49m
> �[38;5;244mE/flutter (31995): #37 Element.inflateWidget�[39;49m
> �[38;5;244mE/flutter (31995): #38 Element.updateChild�[39;49m
> �[38;5;244mE/flutter (31995): #39 ComponentElement.performRebuild�[39;49m
> �[38;5;244mE/flutter (31995): #40 Element.rebuild�[39;49m
> �[38;5;244mE/flutter (31995): #41 ComponentElement._firstBuild�[39;49m
> �[38;5;244mE/flutter (31995): #42 StatefulElement._firstBuild�[39;49m
> �[38;5;244mE/flutter (31995): #43 ComponentElement.mount�[39;49m
> �[38;5;244mE/flutter (31995): #44 Element.inflateWidget�[39;49m
> E/flutter (31995): #45 Element.updateChild (package:flutter/src/widge
> 
> �[38;5;248m════════ Exception Caught By services library ══════════════════════════════════�[39;49m
> �[38;5;244mThe following MissingPluginException was thrown while activating platform stream on channel mobpush_receiver:�[39;49m
> �[38;5;244mMissingPluginException(No implementation found for method listen on channel mobpush_receiver)�[39;49m
> �[38;5;244mWhen the exception was thrown, this was the stack�[39;49m
> �[38;5;244m#0 MethodChannel.invokeMethod�[39;49m
> �[38;5;244m�[39;49m
> �[38;5;244m#1 EventChannel.receiveBroadcastStream.�[39;49m
> �[38;5;244m�[39;49m
> �[38;5;248m#6 Mobpush.addPushReceiver�[39;49m
> �[38;5;244m...�[39;49m
> �[38;5;248m════════════════════════════════════════════════════════════════════════════════�[39;49m

大兄弟，找到解决方法了吗？我也遇到了。

**Comment by 2000calories** [comment]
没有，后来不用了
