### ISSUE TITLE
android 第三方通道配置正确，编译正式版读不了配置

### ISSUE THREAD

**Issue by CyJaySong** [MobClub/MobPush-For-Flutter#8]
已在项目/android/app/build.gradle文件中正确配置 MobSDK ,
flutter run --release 或 flutter build --debug 出来的包都能获取到手机品牌对应的推送通道配置，但是 flutter build --release 出来的，统统 W/MobPushLogger: [MobPush]No more push channel, enter MobPush channel.

**Comment by CyJaySong** [comment]
发现是混淆搞的鬼，按照http://www.mob.com/wiki/detailed?wiki=andronadsifasoifas111&id=136
之中  四.混淆设置 配置后解决

**Comment by elricym** [comment]
@CyJaySong 请问一下混淆设置在哪里？这个wiki好像已经编辑了。
